### ISSUE TITLE
i have a qualcomm robotics RB3 gen2 vision kit

### ISSUE THREAD

**Issue by Thejesh99** [qualcomm-linux/meta-qcom#617]
i have a qualcomm robotics RB3 gen2 vision kit 
can u please provide me a yocto guide for qualcomm robotics RB3 gen2 vision kit 
or any github repo and distro file
Regards
Thejesh

_Originally posted by @Thejesh99 in https://github.com/Linaro/meta-qcom/issues/588#issuecomment-2232578563_

**Comment by Scott31393** [comment]
Hi @Thejesh99,

Pls check https://github.com/Linaro/meta-qcom/issues/616#issuecomment-2246432930
Hope this help :)

Regards,
Tommaso
